all:
  hosts:
    code-server:
      ansible_host: 157.245.54.105
      ansible_user: root
      ansible_ssh_private_key_file: /Users/ebinstanley/.ssh/id_ed25519
      code_server_password: mypassword
      code_server_domain: code-157.245.54.105.nip.io